### ISSUE TITLE
Aprobar TC para Dummies (LaTeX source)

### ISSUE THREAD

**Issue by alvarogirona** [RepoFIBtori/RepoFIBtori#22]
Bones,

El document original que vaig fer està aquí https://www.overleaf.com/read/kvxgqkytmkmq per si el vols penjar i que algú pugui fer correccions/amplicacions o ficar més solucions a problemes.

**Comment by AlbertSuarez** [comment]
Ja es va pujar en el seu moment al [repositori](https://github.com/RepoFIBtori/RepoFIBtori/blob/master/Computacio/TC/Aprobar_TC_para_dummies-10.pdf). Merci @alvarogirona !

**Comment by adriacabeza** [comment]
@alvarogirona  afegiré el link del overleaf per si algu vol continuar amb el legado. És tota una currada, moltes gràcies tiu :D
