### ISSUE TITLE
TI -> SI -> Lab 5 Analisi Codi Malicios

### ISSUE THREAD

**Issue by josopu** [RepoFIBtori/RepoFIBtori#36]
Suposo que al teu any debia ser un altre ordre.
Adjunto respostes del questionari

www.ourgodfather.com
hello
276D07E597FF9AD1D82ACD75F7462F94  <- Falta confirmar
yourpassword@password.com
b. Fecha envio, c. La contr, d. El username

No sé si vols les contribs en PR però em fot molt de pal lol

**Comment by mauriciabad** [comment]
Done
