### ISSUE TITLE
Ajuda amb contribuir

### ISSUE THREAD

**Issue by PauVal99** [RepoFIBtori/RepoFIBtori#43]
Vull afegir les meves pràctiques i problemes de LP, però teniu la carpeta estructurada diferent. La teniu dividida per llenguatges i projectes i no tinc molt clar com afegir el meu repo. Jo el tinc ja estructurat i no el vull dividir en diferents repos. Podeu donar li una ullada aquí [LP](https://github.com/PauVal99/FIB-LP).

**Comment by AlbertSuarez** [comment]
Deixo que @adriacabeza t'assessori amb això.

**Comment by adriacabeza** [comment]
Hola @PauVal99, merci per voler contribuir al projecte :D 

He mirat el teu repo i veig que ho tens estructurat diferent. No passa res, al final el que volem és que hi hagi la màxima informació possible indexada per a tothom. 

Què et sembla tenir quelcom semblant a com està ara però ficant links a subcarpetes del teu repo? i.e. a l'apartat de la pràctica de Haskell afegir un enllaç teu a [https://github.com/PauVal99/FIB-LP/tree/master/Haskell/Pallus](https://github.com/PauVal99/FIB-LP/tree/master/Haskell/Pallus). Crec que és la millor manera per a no trencar l'estructura actual.

**Comment by PauVal99** [comment]
Em sembla be, ara faig un pull request.
